/*
 * This file is generated by jOOQ.
 */
package ch.toubidev.db.jooq.processing;


import ch.toubidev.db.jooq.processing.tables.Category;
import ch.toubidev.db.jooq.processing.tables.User;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MybudgetAppl extends SchemaImpl {

    private static final long serialVersionUID = 1748488532;

    /**
     * The reference instance of <code>mybudget_appl</code>
     */
    public static final MybudgetAppl MYBUDGET_APPL = new MybudgetAppl();

    /**
     * The table <code>mybudget_appl.category</code>.
     */
    public final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>mybudget_appl.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private MybudgetAppl() {
        super("mybudget_appl", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
                Category.CATEGORY,
                User.USER);
    }
}
