/*
 * This file is generated by jOOQ.
 */
package ch.toubidev.db.jooq.processing;


import ch.toubidev.db.jooq.processing.tables.Category;


/**
 * Convenience access to all tables in mybudget_appl
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>mybudget_appl.category</code>.
     */
    public static final Category CATEGORY = Category.CATEGORY;
}
