CREATE TABLE MYBUDGET_APPL.USER
(
    ID       SERIAL PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(100)       NOT NULL,
    EMAIL    VARCHAR(150)       NOT NULL,
    PASSWORD VARCHAR(200)       NOT NULL
);