server:
  port: 8080

spring:
  datasource:
    url: ${MYBUDGET_DB_URL}
    username: ${MYBUDGET_DB_USERNAME}
    password: ${MYBUDGET_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      maximumPoolSize: 100
    jooq:
      sqlDialect: POSTGRESQL

mybudget:
  build:
    artifactId: "${project.artifactId}"
    version: "${project.version}"
    timestamp: "${timestamp}"
    gitCommit: "${buildNumber}"